// <auto-generated />
using System;
using ControleAcesso.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleAcesso.Infraestrutura.Migrations
{
    [DbContext(typeof(ControleAcessoContext))]
    [Migration("20220314135510_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleAcesso.Class.Movimentos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sentido")
                        .HasColumnType("int");

                    b.Property<int>("StatusMovimento")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimento")
                        .HasColumnType("int");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Movimentos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Movimentos");
                });

            modelBuilder.Entity("ControleAcesso.Class.Pessoas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ControleAcesso.Class.Veiculos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.NotasFiscais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMovimento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MovimentosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroNotaFiscal")
                        .HasColumnType("int");

                    b.Property<double>("PesoNotaFiscal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MovimentosId");

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.Observacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMovimento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MovimentosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovimentosId");

                    b.ToTable("Observacao");
                });

            modelBuilder.Entity("ControleAcesso.Class.MovimentosPesagem", b =>
                {
                    b.HasBaseType("ControleAcesso.Class.Movimentos");

                    b.Property<double>("PesoChegada")
                        .HasColumnType("float");

                    b.Property<double>("PesoSaida")
                        .HasColumnType("float");

                    b.Property<string>("StatusPesagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPesoNotaFiscal")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("MovimentosPesagem");
                });

            modelBuilder.Entity("ControleAcesso.Class.SaidaCarroEmpresa", b =>
                {
                    b.HasBaseType("ControleAcesso.Class.Movimentos");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraEntrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraSaida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KmEntrada")
                        .HasColumnType("int");

                    b.Property<int>("KmSaida")
                        .HasColumnType("int");

                    b.Property<int>("NivelCombustivelEntrada")
                        .HasColumnType("int");

                    b.Property<int>("NivelCombustivelSaida")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SaidaCarroEmpresa");
                });

            modelBuilder.Entity("ControleAcesso.Class.Movimentos", b =>
                {
                    b.HasOne("ControleAcesso.Class.Pessoas", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleAcesso.Class.Veiculos", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.NotasFiscais", b =>
                {
                    b.HasOne("ControleAcesso.Class.Movimentos", null)
                        .WithMany("NotasFiscais")
                        .HasForeignKey("MovimentosId");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.Observacao", b =>
                {
                    b.HasOne("ControleAcesso.Class.Movimentos", null)
                        .WithMany("Observacoes")
                        .HasForeignKey("MovimentosId");
                });

            modelBuilder.Entity("ControleAcesso.Class.Movimentos", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Observacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
