// <auto-generated />
using System;
using ControleAcesso.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleAcesso.Infraestrutura.Migrations
{
    [DbContext(typeof(ControleAcessoContext))]
    partial class ControleAcessoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleAcesso.Class.EntradaFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sentido")
                        .HasColumnType("int");

                    b.Property<int>("StatusMovimento")
                        .HasColumnType("int");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("EntradasFuncionarios", (string)null);
                });

            modelBuilder.Entity("ControleAcesso.Class.MovimentoPesagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("PesoChegada")
                        .HasColumnType("float");

                    b.Property<double>("PesoSaida")
                        .HasColumnType("float");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sentido")
                        .HasColumnType("int");

                    b.Property<int>("StatusMovimento")
                        .HasColumnType("int");

                    b.Property<string>("StatusPesagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPesoNotaFiscal")
                        .HasColumnType("float");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("MovimentosPesagem");
                });

            modelBuilder.Entity("ControleAcesso.Class.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ControleAcesso.Class.SaidaCarroEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraSaida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KmEntrada")
                        .HasColumnType("int");

                    b.Property<int>("KmSaida")
                        .HasColumnType("int");

                    b.Property<int?>("NivelCombustivelEntrada")
                        .HasColumnType("int");

                    b.Property<int>("NivelCombustivelSaida")
                        .HasColumnType("int");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sentido")
                        .HasColumnType("int");

                    b.Property<int>("StatusMovimento")
                        .HasColumnType("int");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("SaidasCarrosEmpresa", (string)null);
                });

            modelBuilder.Entity("ControleAcesso.Class.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntradaFuncionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMovimento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MovimentoPesagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroNotaFiscal")
                        .HasColumnType("int");

                    b.Property<double>("PesoNotaFiscal")
                        .HasColumnType("float");

                    b.Property<Guid?>("SaidaCarroEmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntradaFuncionarioId");

                    b.HasIndex("MovimentoPesagemId");

                    b.HasIndex("SaidaCarroEmpresaId");

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.Observacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntradaFuncionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMovimento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MovimentoPesagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SaidaCarroEmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntradaFuncionarioId");

                    b.HasIndex("MovimentoPesagemId");

                    b.HasIndex("SaidaCarroEmpresaId");

                    b.ToTable("Observacoes");
                });

            modelBuilder.Entity("ControleAcesso.Class.EntradaFuncionario", b =>
                {
                    b.HasOne("ControleAcesso.Class.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleAcesso.Class.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("ControleAcesso.Class.MovimentoPesagem", b =>
                {
                    b.HasOne("ControleAcesso.Class.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleAcesso.Class.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("ControleAcesso.Class.SaidaCarroEmpresa", b =>
                {
                    b.HasOne("ControleAcesso.Class.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleAcesso.Class.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.NotaFiscal", b =>
                {
                    b.HasOne("ControleAcesso.Class.EntradaFuncionario", null)
                        .WithMany("NotasFiscais")
                        .HasForeignKey("EntradaFuncionarioId");

                    b.HasOne("ControleAcesso.Class.MovimentoPesagem", null)
                        .WithMany("NotasFiscais")
                        .HasForeignKey("MovimentoPesagemId");

                    b.HasOne("ControleAcesso.Class.SaidaCarroEmpresa", null)
                        .WithMany("NotasFiscais")
                        .HasForeignKey("SaidaCarroEmpresaId");
                });

            modelBuilder.Entity("ControleAcesso.Domain.Modelos.Observacao", b =>
                {
                    b.HasOne("ControleAcesso.Class.EntradaFuncionario", null)
                        .WithMany("Observacoes")
                        .HasForeignKey("EntradaFuncionarioId");

                    b.HasOne("ControleAcesso.Class.MovimentoPesagem", null)
                        .WithMany("Observacoes")
                        .HasForeignKey("MovimentoPesagemId");

                    b.HasOne("ControleAcesso.Class.SaidaCarroEmpresa", null)
                        .WithMany("Observacoes")
                        .HasForeignKey("SaidaCarroEmpresaId");
                });

            modelBuilder.Entity("ControleAcesso.Class.EntradaFuncionario", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Observacoes");
                });

            modelBuilder.Entity("ControleAcesso.Class.MovimentoPesagem", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Observacoes");
                });

            modelBuilder.Entity("ControleAcesso.Class.SaidaCarroEmpresa", b =>
                {
                    b.Navigation("NotasFiscais");

                    b.Navigation("Observacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
